# Generated by Django 6.0.3 on 2026-03-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
            ],
        ),
    ]
