# Generated by Django 6.0.3 on 2026-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(max_length=50),
        ),
    ]
